using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace GeneratedNamespace.Tests
{

    [TestFixture]
    public class Test13Test
    {
        [Test]
        public void Method1Test()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method3Test()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method4Test()
        {
            Assert.Fail("autogenerated");
        }

    }
}